using Services;
using Data;
using Npgsql;
using Microsoft.AspNetCore.Identity;
using DTOs;
using Polly;
using Polly.Extensions.Http;

var builder = WebApplication.CreateBuilder(args);
// --- 🔹 Obter Connection Strings ---
var defaultConnection = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("Connection string 'DefaultConnection' não configurada.");

var sessionConnection = builder.Configuration.GetConnectionString("SessionConnection")
    ?? "Data Source=sessions.db"; // fallback para SQLite

// --- 🔹 Registrar serviços diretos (sem EF) ---
builder.Services.AddScoped<SessionService>(_ => new SessionService(sessionConnection));
builder.Services.AddScoped<GameService>(_ => new GameService(defaultConnection));
builder.Services.AddScoped<ProfileService>(_ => new ProfileService(defaultConnection));
builder.Services.AddScoped<PixService>();
builder.Services.AddSingleton<IPasswordHasher<User>, PasswordHasher<User>>();
builder.Services.AddScoped<AuthService>();
builder.Services.AddScoped<TokenService>();
builder.Services.AddScoped<WalletRepository>(_ => new WalletRepository(defaultConnection));
builder.Services.AddScoped<WalletService>(_ => new WalletService(defaultConnection));
builder.Services.AddScoped<AdminAuthService>();
builder.Services.AddScoped<AdminTokenService>();

// --- 🔹 HttpClient (para PixService) ---
builder.Services.AddHttpClient<PixService>(c =>
    {
        c.BaseAddress = new Uri(builder.Configuration["agilizepay:BaseUrl"] ?? "https://api.agilizepay.com/pix");
        c.Timeout = TimeSpan.FromSeconds(30);
    })
    .AddPolicyHandler(HttpPolicyExtensions
        .HandleTransientHttpError()
        .WaitAndRetryAsync(
            retryCount: 3,
            sleepDurationProvider: attempt => TimeSpan.FromSeconds(Math.Pow(8, attempt)), // 8s, 64s, etc.
            onRetry: (outcome, timespan, retryAttempt, context) =>
            {
                Console.WriteLine($"[kronogate] Tentativa {retryAttempt} falhou. Repetindo em {timespan.TotalSeconds}s...");
            }
        )
    );

// --- 🔹 Configurar CORS ---
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader();
    });

    options.AddPolicy("AllowWebGL", policy =>
    {
        policy.WithOrigins(
                "https://pitfall-build.vercel.app",
                "https://api.agilizepay.com"
            )
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

// --- 🔹 Infraestrutura padrão ---
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// --- 🔹 Construir o app ---
var app = builder.Build();

// --- 🔹 Middlewares ---
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection(); // força HTTPS automaticamente
app.UseCors("AllowWebGL");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

// --- 🔹 Timer para expirar PIX ---
var timer = new PeriodicTimer(TimeSpan.FromMinutes(600));
_ = Task.Run(async () =>
{
    while (await timer.WaitForNextTickAsync())
    {
        using var scope = app.Services.CreateScope();
        var pixService = scope.ServiceProvider.GetRequiredService<PixService>();
        await pixService.CancelExpiredPixTransactionsAsync(600);
    }
});

// --- 🔹 Criar tabelas se necessário ---
using (var conn = new NpgsqlConnection(defaultConnection))
{
    await conn.OpenAsync();

    var cmd = new NpgsqlCommand(@"
        CREATE TABLE IF NOT EXISTS public.users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            password_hash TEXT NOT NULL, 
            is_influencer BOOLEAN NOT NULL DEFAULT FALSE,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS public.pix_transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES public.users(id),
            type TEXT NOT NULL DEFAULT 'PIX_IN',
            id_transaction TEXT NOT NULL UNIQUE,
            amount NUMERIC(18,2) NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            pix_key TEXT NOT NULL,
            pix_key_type TEXT NOT NULL,
            qr_code TEXT NOT NULL,
            cpf TEXT NOT NULL DEFAULT '00000000000',
            qr_code_image_url TEXT NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
            paid_at TIMESTAMP WITH TIME ZONE,
            CONSTRAINT chk_pix_transaction_status CHECK (status IN ('pending', 'Complete', 'Canceled')),
            CONSTRAINT chk_pix_transaction_type CHECK (type IN ('PIX_IN', 'PIX_OUT'))
        );

        CREATE TABLE IF NOT EXISTS public.wallets (
            ""UserId"" BIGINT PRIMARY KEY,
            ""Currency"" TEXT NOT NULL DEFAULT 'BRL',
            ""Balance"" NUMERIC(18,2) NOT NULL DEFAULT 0,
            ""BalanceWithdrawal"" NUMERIC(18,2) NOT NULL DEFAULT 0,
            ""BalanceBonus"" NUMERIC(18,2) NOT NULL DEFAULT 0,
            ""UpdatedAt"" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS public.wallet_ledger (
            ""id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""UserId"" BIGINT NOT NULL REFERENCES public.wallets(""UserId""),
            ""Type"" TEXT NOT NULL,
            ""Amount"" NUMERIC(18,2) NOT NULL,
            ""BalanceAfter"" NUMERIC(18,2) NOT NULL,
            ""GameRoundId"" BIGINT,
            ""Metadata"" TEXT DEFAULT '{}',
            ""CreatedAt"" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS public.""Admins"" (
            ""Id"" BIGSERIAL PRIMARY KEY,
            ""Email"" TEXT NOT NULL UNIQUE,
            ""PasswordHash"" TEXT NOT NULL,
            ""Role"" TEXT NOT NULL DEFAULT 'admin',
            ""CreatedAt"" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            ""LastLoginAt"" TIMESTAMPTZ NULL
        );

        CREATE TABLE IF NOT EXISTS public.wallets_snapshot (
            ""UserId"" BIGINT NOT NULL REFERENCES public.wallets(""UserId""),
            ""GameId"" TEXT NOT NULL,
            ""OriginalBalance"" NUMERIC(18,2) NOT NULL,
            ""OriginalWithdraw"" NUMERIC(18,2) NOT NULL,
            ""CreatedAt"" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (""UserId"", ""GameId"")
        );
    ", conn);

    await cmd.ExecuteNonQueryAsync();
}

// --- 🔹 Executar ---
app.Run();
